import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import React from "react";
import Header from "@/components/layouts/main/Header";
import Footer from "@/components/layouts/main/Footer";
import ReduxProvider from "@/redux/provider";
import ThemeContextProvider from "@/context/theme-context";
import ThemeSwitch from "@/components/elements/ThemeSwitch";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`font-HelveticaRegular bg-background dark:bg-dark-500 ${inter.className}`}>
    <ThemeContextProvider>
      <ReduxProvider>
        {children}
        <ThemeSwitch/>
      </ReduxProvider>
    </ThemeContextProvider>
    </body>
    </html>
  )
}
